WHITESPACE = _{ " " | "\t" }

pretty_much_anything = { !(WHITESPACE | NEWLINE | "," | ":") ~ ANY }

value = @{ pretty_much_anything+ }
name = @{ pretty_much_anything+ }

comment = { "#" ~ (!NEWLINE ~ ANY)* }

alias = { name ~ ":=" ~ value }
label = { name ~ ":" }
op = { name ~ (value ~ (","? ~ value)*)? }
empty = @{ WHITESPACE* }

line = _{ (comment | alias | label | op | empty) ~ NEWLINE }

program = _{SOI ~ line* ~ EOI}
